geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='products'),
]

geekshop/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')

geekshop/mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(
        max_length=64,
        verbose_name='имя',
        unique=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    updated = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )

    image = models.ImageField(
        upload_to='products_images',
        blank=True
    )

    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=60,
        blank=True,
    )

    description = models.TextField(
        verbose_name='описание продукта',
        blank=True,
    )

    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='цена',
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    updated = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    class Meta:
        ordering = ['-updated']
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

geekshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

geekshop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from  django.urls import reverse

from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    context = {
        'title': title,
        'login_form': login_form
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    context = {
        'title': title,
        'register_form': register_form
    }

    return render(request, 'authapp/register.html', context)


def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    context = {
        'title': title,
        'edit_form': edit_form
    }

    return render(request, 'authapp/edit.html', context)

geekshop/geekshop/views.py
from django.shortcuts import render

from mainapp.models import Product


def main(request):
    title = 'Магазин'

    products = Product.objects.all()[:4]

    context = {
        'title': title,
        'products': products,
    }
    return render(request, 'geekshop/index.html', context)


def contacts(request):
    title = 'Контакты'

    context = {
        'title': title,
    }
    return render(request, 'geekshop/contact.html', context)

geekshop/mainapp/views.py
from django.shortcuts import render

from mainapp.models import ProductCategory


def products(request):
    title = 'Каталог'
    links_menu = ProductCategory.objects.all()
    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'mainapp/products.html', context)

geekshop/authapp/templates/authapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <title>{{ title|title }}</title>
</head>
<body>
<div class="container">
    <div class="row center py-4">
    <div class="col-4"></div>
        <div class="col-4">
            {% block content %}
            {% endblock %}
        </div>
    <div class="col-4"></div>
    </div>
</div>

</body>
</html>

geekshop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}

{% load static %}
{% block content %}
    <img src="/media/{{ user.avatar|default:'user-place-holder.png' }}" class="w-25">
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype=multipart/form-data>
        {% csrf_token %}
        {{ edit_form.as_p }}
      <button type="submit" class="btn btn-primary">Изменить</button>
    </form>
    <button class="btn btn-round form-control">
        <a href="{% url 'main' %}" class="">
            На главную
        </a>
    </button>
{% endblock %}

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% load static %}
{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
      <button type="submit" class="btn btn-primary">Войти</button>
    </form>
    <button class="btn btn-round form-control">
        <a href="{% url 'auth:register' %}" class="">
            зарегистрироваться
        </a>
    </button>
{% endblock %}

geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}

{% load static %}
{% block content %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post">
        {% csrf_token %}
        {{ register_form.as_p }}
      <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
    <button class="btn btn-round form-control">
        <a href="{% url 'auth:login' %}" class="">
            Войти
        </a>
    </button>
{% endblock %}

geekshop/geekshop/templates/geekshop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
		{% block title %}
            {{ title|title }}
        {% endblock %}
	</title>
	{% block css %}
	{% endblock %}
	<link rel="stylesheet" type="text/css" href="{% static 'geekshop/style.css' %}">
	<link rel="stylesheet" href="{% static 'geekshop/fonts/font-awesome/css/font-awesome.css' %}">
</head>
<body>
	<div class="container">
		{% block content %}
        {% endblock %}

		<div class="clr"></div>

	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

    {% block js %}
    {% endblock %}

</body>
</html>

geekshop/geekshop/templates/geekshop/contact.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block content %}
		<div class="hero">
			<div class="header clearfix">
				<a href="/" class="logo"></a>
				<ul class="menu">
					<li><a href="/">домой</a></li>
					<li><a href="/products/">продукты</a></li>
					<li><a href="/contacts/" class="active">контакты</a></li>
				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>
{% endblock %}

geekshop/geekshop/templates/geekshop/includes/block.html
<div class="block">
					<a href="#"><img src="img/product-2.jpg" alt="">
						<div class="text">
							<img src="img/icon-hover.png" alt="">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>

geekshop/geekshop/templates/geekshop/includes/slider.html
{% load static %}
<div class="slider">
			<div class="header clearfix">
				Добро пожаловать на наш сайт, {{ user.first_name|title}} {{ user.last_name|title}}
				<a href="{% url 'main' %}" class="logo"></a>
				<ul class="menu">
					<li><a href="{% url 'main' %}" class="active">домой</a></li>
					<li><a href="{% url 'products' %}">продукты</a></li>
					<li><a href="{% url 'contacts' %}">контакты</a></li>
				</ul>
				<a href="#" class="search"></a>
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции {% now "Y" %}</h3>
				{% if user.is_authenticated %}
					<h3 class="big"> удобные стулья</h3>
				{% else %}
					<h3 class="big"> стулья закончились </h3>
				{% endif %}
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
			</div>
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

geekshop/geekshop/templates/geekshop/index.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block css %}
{% endblock %}

{% block content %}
	{% include 'geekshop/includes/slider.html' %}


		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for product in products %}
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/product-1.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{ product.short_desc }}</h4>
                                <p>{{ product.description }}</p>
							</div>
						</a>
					</div>
				{% endfor %}

			</div>
		</div>

{% endblock %}
		

geekshop/mainapp/templates/mainapp/products.html
{% extends 'geekshop/base.html' %}
{% load static %}
{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
{% endblock %}
{% block content %}
		<div class="hero-white">
			<div class="header clearfix">
				<a href="/" class="logo"></a>
				<ul class="menu">
					<li><a href="/">домой</a></li>
					<li><a href="/products/" class="active">продукты</a></li>
					<li><a href="/contacts/">контакты</a></li>

				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
		</div>

		<div class="details">
			<div class="links clearfix">
				{{ request.resolver_match.url_name }}
				<ul class="links-menu">
                    {% for link in links_menu %}
					    <li><a href="{{ link.href }}" class="{% if request.resolver_match.url_name == link.href %}
                        active
                      {% endif %}">{{ link.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{% static 'geekshop/img/slider1.jpg' %}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="img/controll.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="img/controll1.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="img/controll2.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p> 
						<p>Отличное качество материалов
						позволит вам это.</p> 
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="img/product-11.jpg" alt="">
							<div class="text">
								<img src="img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="img/product-21.jpg" alt="">
							<div class="text">
								<img src="img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="img/product-31.jpg" alt="">
							<div class="text">
								<img src="img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>
{% endblock %}